### PR TITLE
docs: update docs with packages descriptions

### PR DESCRIPTION
**Pull request by r4topunk**
As a new contributor to the repo, I initially found it challenging to navigate the repository, particularly given its monorepo structure. To assist future newcomers in quickly understanding the purpose and functionality of each package, I've added concise yet comprehensive descriptions for each sub-repository in the main README file.

This update aims to make the monorepo more welcoming and informative, providing a clearer starting point for new developers interested in contributing to the Gnars project.

### CODE REVIEW

**Comment by sktbrd** [comment]
Thanks R4to ! Its going to be reviewed

**Review by mulfdev — CHANGES_REQUESTED** [review]
Thanks for the pr!

It seems like this mostly just explains what can be determined by looking at the code repo itself. Let's revise to include information which isn't quite so obvious. Or condense the explanations. Both or either would be ok

And not copy and paste from chat GPT quite so obviously.

**Comment by r4topunk** [comment]
@mulfdev 

I did it to start a documentation in a poorly documented repo, it's literally the copy of every inner package, but in the initial readme so people can visit the repo and see what's inside.

It's not write in rock, it's a start for you guys who really know the code to update the docs of the code you created.

As I said, this is my first contact with the repo, it's fine to not accept the PR, but then create a better document from this one.

**Comment by sktbrd** [comment]
I see Mulfs points, but also agree that is better than zero ReadMe and we can evolve from there

**Comment by r4topunk** [comment]
I agree with him too 🤷🏽‍♂️

**Comment by mulfdev** [comment]
Feel free to rewrite in your own words. I use ChatGPT as well but this is overly verbose and nonspecific in a bunch of ways.

**Comment by r4topunk** [comment]
I will rewrite with a better analysis of the context and the code. I don't have much experience in creating very good readmes, but I gona try hard

Sorry for being rude @mulfdev, but I was trying to help in my way, with a step, and I felt too unwelcome :/

**Comment by r4topunk** [comment]
@mulfdev can you please review again?

I think this is as deep as I can go to briefly explain each package.

**Pull request closed without merging**
