### PR TITLE
fix GnarInfo text color

### PR DESCRIPTION
**Pull request by sktbrd**
fixed homepage text color bug in small screens

### CODE REVIEW

**Review by asmattic — CHANGES_REQUESTED** [review]
Can you center both lines of test on mobile and I'll complete approval

**Review by 0xMillz — COMMENTED** [review]
"mean time" is actually one-word (meantime) so I made a PR on your branch to fix the typo

**Review by asmattic — CHANGES_REQUESTED** [review]
I updated `GnarInfo.tsx` to be more mobile friendly. Can you make these changes in `packages/webapp/components/Explainer.tsx` in the image below and I'll merge it.

image

**Comment by asmattic** [comment]
> I updated `GnarInfo.tsx` to be more mobile friendly. Can you make these changes in `packages/webapp/components/Explainer.tsx` in the image below and I'll merge it.
> 
> image

---

image

### And it looks like this on mobile.

I also fixed up the base migration alert on mobile but I'll just push that in it's own PR.

----

image

**Review by asmattic — APPROVED** [review]

**Comment by asmattic** [comment]
I just went ahead and made the changes requested. It's only a style change and I've tested so I'm going ahead with the merge.

**Pull request merged**
